### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by paperclipstudio** [paperclipstudio/Func-Mapper#1]
- [ ] change from one file only to a whole folder
- [x] Create a GUI
- [ ] Improve the rendering system
- [ ] Create classes for 
- [ ] code_blocks
